languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Victor Yuan"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["samples"]
  description = "Wander world"

[params.author]
  name = "Victor Yuan"
  image = "img/author.jpg"
  headline = "Bioinformatics Scientist :bar_chart:"
  bio = ":dog: :maple_leaf:"
  links = [
    { github = "https://github.com/wvictor14" },
    { linkedin = "https://linkedin.com/" },
  ]